[meta]
title = "C# Transcription Starter"
description = "Get started using Deepgram's Transcription with this C# demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "Prerecorded"
language = "C#"
framework = ".NET"

[build]
command = "dotnet restore"

[config]
sample = ".env-sample"
output = ".env"

[post-build]
message = "dotnet run"
